Repository AtomBombf13/AtomBomb, pull requests merged in 2022-12, with the labels that each got.

#184 Readds Plasmusketry
  code/__DEFINES/ammo.dm
  code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
  code/modules/projectiles/ammunition/caseless/_caseless.dm
  code/modules/projectiles/boxes_magazines/ammo_boxes.dm
  code/modules/projectiles/boxes_magazines/internal/shotgun.dm
  code/modules/projectiles/guns/hoboguns.dm
Labels: stale

#286 Moves G&B 2 to low trait book spawner
  code/game/objects/effects/spawners/f13lootdrop.dm
Labels: Balance

#287 Christmas Tree changes.
  code/game/objects/items/gift.dm
  code/game/objects/structures/flora.dm
Labels: Feature

#279 Reupload access fixes for BoS
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
  code/game/machinery/computer/robot.dm
  code/game/machinery/computer/security.dm
  code/game/machinery/dance_machine.dm
  code/game/machinery/navbeacon.dm
  code/game/machinery/shieldgen.dm
  code/game/objects/items/cards_ids.dm
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  code/modules/admin/secrets.dm
  code/modules/atmospherics/machinery/airalarm.dm
  code/modules/atmospherics/machinery/portable/canister.dm
  code/modules/cargo/packs/emergency.dm
  code/modules/cargo/packs/organic.dm
  code/modules/jobs/job_types/bos.dm
  code/modules/jobs/job_types/eastwood.dm
  code/modules/mob/living/brain/posibrain.dm
  code/modules/mob/living/silicon/robot/robot_defines.dm
  code/modules/mob/living/simple_animal/bot/bot.dm
  code/modules/mob/living/simple_animal/bot/cleanbot.dm
  code/modules/mob/living/simple_animal/bot/firebot.dm
  code/modules/mob/living/simple_animal/bot/floorbot.dm
  code/modules/mob/living/simple_animal/bot/medbot.dm
  code/modules/modular_computers/file_system/programs/borg_monitor.dm
  code/modules/modular_computers/file_system/programs/powermonitor.dm
  code/modules/modular_computers/file_system/programs/robocontrol.dm
  code/modules/power/apc.dm
  code/modules/power/singularity/collector.dm
  code/modules/power/singularity/emitter.dm
  code/modules/research/nanites/nanite_remote.dm
  code/modules/vehicles/mecha/mech_fabricator.dm
  code/modules/vehicles/mecha/mecha_control_console.dm
Labels: Bugfix, Mapping

#277 Top right button colors
  tgui/packages/tgui-panel/themes.js
  tgui/public/tgui-panel.bundle.js
Labels: UI

#274 a gift for chairman cheng
  code/modules/mob/living/simple_animal/hostile/f13/wastebots.dm
  sound/f13npc/liberator/liberator_aggro1.ogg
  sound/f13npc/liberator/liberator_aggro2.ogg
  sound/f13npc/liberator/liberator_taunt1.ogg
Labels: Feature, Sprites

#284 Adds 3 new clothes to charselect loadout and changes description of 1 clothing item
  code/modules/clothing/under/f13.dm
  modular_citadel/code/modules/client/loadout/uniform.dm
Labels: Feature

#281 Fixes looping weather sounds and updates them
  code/controllers/subsystem/timer.dm
  code/datums/components/area_sound_manager.dm
  code/datums/looping_sounds/_looping_sound.dm
  code/datums/weather/weather.dm
  code/datums/weather/weather_types/rain.dm
Labels: Bugfix

#282 Removes the memory loss text from being revived
  code/modules/fallout/obj/smelling_salts.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/surgery/advanced/revival.dm
  modular_citadel/code/modules/reagents/chemistry/reagents/healing.dm
Labels: Feature

#261 slightly diversifies random body
  code/modules/mob/dead/new_player/preferences_setup.dm
Labels: Code Optimization/Refactor

#290 Anvil Template Idiotproofing
  modular_atom/blacksmith/anvil.dm
Labels: Sprites, Code Optimization/Refactor

#306 Brave Bull gives you Fearless
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
Labels: Feature

#302 PA book from machine gone
  code/modules/WVM/wvm.dm
Labels: Balance

#310 No more Infinite Drug happiness
  code/datums/mood_events/drug_events.dm
Labels: Balance

#309 Removes the create-area verb
  code/_onclick/hud/generic_dextrous.dm
  code/_onclick/hud/human.dm
  code/_onclick/hud/screen_objects.dm
  tgui/public/tgui.bundle.css
Labels: Bugfix, Removal

#301 Reduces the zoom amount of the DKS and the dead-eye scope.
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/guns/mods/mods.dm
Labels: Balance

#307 Binos fit on neckslot
  code/game/objects/items/binoculars.dm
  icons/mob/clothing/neck.dmi
Labels: Feature, Sprites

#319 Reenables death timers
  code/__DEFINES/misc.dm
  code/controllers/configuration/entries/general.dm
  code/game/data_huds.dm
  code/game/objects/items/defib.dm
  code/game/objects/items/devices/scanners.dm
  code/modules/clothing/neck/_neck.dm
  code/modules/fallout/obj/smelling_salts.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/death.dm
  config/config.txt
  modular_citadel/code/modules/reagents/chemistry/reagents/healing.dm
Labels: Feature

#298 v.1.1_Fashion
  atombomb.dme
  code/modules/clothing/head/f13head.dm
  code/modules/clothing/suits/light_armor.dm
  code/modules/clothing/suits/suits.dm
  code/modules/clothing/under/f13.dm
  code/modules/jobs/job_types/eastwood.dm
  code/modules/mob/living/carbon/human/species.dm
  modular_atom/fashion/README.md
  modular_atom/fashion/code/clothing.dm
  modular_atom/fashion/code/clothing_fashion.dm
  modular_atom/fashion/code/cosmetics.dm
  modular_atom/fashion/code/hair_face.dm
  modular_atom/fashion/icons/clothing.dmi
  modular_atom/fashion/icons/clothing_fashion.dmi
  modular_atom/fashion/icons/cosmetics.dmi
  modular_atom/fashion/icons/facial_hair.dmi
  modular_atom/fashion/icons/facial_hair_extensions.dmi
  modular_atom/fashion/icons/hair.dmi
  modular_atom/fashion/icons/hair_extensions.dmi
  modular_atom/fashion/icons/onmob.dmi
  modular_atom/fashion/icons/onmobleft.dmi
  modular_atom/fashion/icons/onmobright.dmi
  modular_atom/fashion/preview.dmi
  modular_atom/fashion/sound/shaving.ogg
  modular_citadel/code/modules/client/loadout/backpack.dm
  modular_citadel/code/modules/client/loadout/head.dm
  modular_citadel/code/modules/client/loadout/shoes.dm
  modular_citadel/code/modules/client/loadout/uniform.dm
Labels: Feature, Sprites

#318 Reworked all accesses and mapping fixes
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
  code/__DEFINES/access.dm
  code/game/machinery/cloning.dm
  code/game/machinery/computer/card.dm
  code/game/machinery/computer/medical.dm
  code/game/machinery/computer/security.dm
  code/game/machinery/dance_machine.dm
  code/game/machinery/doors/airlock_electronics.dm
  code/game/objects/items/RCD.dm
  code/game/objects/items/cards_ids.dm
  code/game/objects/items/circuitboards/computer_circuitboards.dm
  code/game/objects/structures/barsigns.dm
  code/game/objects/structures/crates_lockers/closets/secure/bar.dm
  code/game/objects/structures/crates_lockers/closets/secure/freezer.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/jobs/access.dm
  code/modules/jobs/job_types/bos.dm
  code/modules/jobs/job_types/eastwood.dm
  code/modules/jobs/job_types/enclave.dm
  code/modules/jobs/job_types/khan.dm
  code/modules/jobs/job_types/legion.dm
  code/modules/jobs/job_types/ncr.dm
  code/modules/jobs/job_types/wasteland.dm
  code/modules/mining/mine_items.dm
  code/modules/modular_computers/file_system/programs/card.dm
  code/modules/vending/snack.dm
Labels: Mapping, Code Optimization/Refactor

#313 Removes gitignore files that are on the repo
  tgui/public/tgui.bundle.css
  tgui/public/tgui.bundle.js
Labels: Removal

#303 wastelanders learn to aim
  code/__DEFINES/combat.dm
  code/modules/projectiles/projectile/bullets/rifle.dm
Labels: Balance

#317 Re-adds NCR Helmets + NCR accessory tweaks
  code/modules/clothing/head/f13factionhead.dm
  code/modules/clothing/under/accessories.dm
  code/modules/jobs/job_types/ncr.dm
  icons/fallout/clothing/hats.dmi
  icons/fallout/onmob/clothes/head.dmi
  icons/mob/clothing/accessories.dmi
  icons/obj/clothing/accessories.dmi
  modular_citadel/code/modules/client/loadout/head.dm
Labels: Feature, Sprites

#305 Re-activating BoS Off-Duty to spawn listing and fixied naming paths, slot machine and added deathchat toggle.
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
  code/game/machinery/slotmachine.dm
  code/modules/client/preferences_toggles.dm
  code/modules/jobs/job_types/bos.dm
  code/modules/jobs/jobs.dm
  modular_citadel/code/modules/client/loadout/head.dm
  modular_citadel/code/modules/client/loadout/uniform.dm
Labels: Bugfix

#320 THE... AER-family buff.
  code/modules/projectiles/projectile/beams.dm
Labels: Balance

#285 weapon tweaks
  code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
  code/game/objects/effects/spawners/f13lootdrop.dm
  code/game/objects/items/granters.dm
  code/game/objects/items/melee/f13powerfist.dm
  code/game/objects/items/melee/f13twohanded.dm
  code/game/objects/items/storage/f13storage.dm
  code/modules/jobs/job_types/bos.dm
  code/modules/jobs/job_types/eastwood.dm
  code/modules/jobs/job_types/enclave.dm
  code/modules/power/cell.dm
  code/modules/projectiles/ammunition/caseless/_caseless.dm
  code/modules/projectiles/ammunition/energy/laser.dm
  code/modules/projectiles/ammunition/energy/plasma.dm
  code/modules/projectiles/boxes_magazines/ammo_boxes.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/guns/energy/plasmaf13.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/projectiles/projectile/bullets/pistol.dm
Labels: Balance

#323 Makes Brahmins not ridable awhile they are dead.
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
Labels: Bugfix

#312 Removes Venator +1 Vex slot
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
  code/__DEFINES/jobs.dm
  code/game/objects/effects/landmarks.dm
  code/game/objects/items/cards_ids.dm
  code/modules/jobs/job_types/legion.dm
  code/modules/jobs/jobs.dm
Labels: Balance

#333 Wound Descriptions
  code/datums/components/crafting/recipes/recipes_medicine.dm
  code/datums/wounds/bones.dm
  code/datums/wounds/burns.dm
  code/datums/wounds/pierce.dm
  code/datums/wounds/slash.dm
  code/game/objects/items/stacks/medical.dm
  code/modules/fallout/obj/food_and_drinks/wastefood.dm
  code/modules/fallout/reagents/medicines.dm
  code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  code/modules/reagents/chemistry/recipes/chemrecipes-fallout.dm
  code/modules/reagents/reagent_containers/patch.dm
  modular_atom/blacksmith/icons/onmob/lefthand.dmi
  modular_atom/blacksmith/icons/onmob/righthand.dmi
Labels: Feature

#342 HN needler dart quick fix
  code/modules/projectiles/projectile/bullets/pistol.dm
Labels: Bugfix

#308 Vendor upgrade 1
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
  code/modules/WVM/wmv_buyer.dm
  code/modules/WVM/wvm.dm
  icons/WVM/new_vendors.dmi
  testing.dmm
Labels: Feature, Sprites

#293 role balances and changes
  code/modules/jobs/job_types/bos.dm
Labels: Balance

#349 En-Mass name changing
  code/game/objects/effects/decals/cleanable/robots.dm
  code/game/objects/effects/decals/remains.dm
  code/game/objects/items/stacks/tiles/tile_types.dm
  code/game/objects/items/storage/toolbox.dm
  code/game/objects/structures/crates_lockers/crates/bins.dm
  code/game/objects/structures/dresser.dm
  code/game/objects/structures/flora.dm
  code/game/objects/structures/morgue.dm
  code/game/objects/structures/showcase.dm
  code/game/objects/structures/signs/signs_departments.dm
  code/game/objects/structures/signs/signs_maps.dm
  code/modules/clothing/outfits/ert.dm
  code/modules/events/spacevine.dm
  code/modules/holodeck/items.dm
  code/modules/mining/machine_silo.dm
  code/modules/paperwork/pen.dm
  code/modules/paperwork/photocopier.dm
  code/modules/paperwork/stamps.dm
  code/modules/photography/photos/frame.dm
  code/modules/uplink/uplink_items/uplink_badass.dm
  code/modules/vending/boozeomat.dm
  code/modules/vending/clothesmate.dm
  code/modules/vending/dinnerware.dm
  code/modules/vending/engivend.dm
  code/modules/vending/games.dm
  code/modules/vending/megaseed.dm
  code/modules/vending/robotics.dm
  modular_coyote/code/flora_coyote.dm
Labels: Feature

#348 Skull helmet fix
  code/modules/clothing/head/f13head.dm
  code/modules/clothing/head/helmet.dm
Labels: Balance

#325 weapon tweaks pt2
  code/modules/projectiles/ammunition/energy/laser.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/guns/ballistic/minigun.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/projectiles/projectile/bullets/rifle.dm
  code/modules/projectiles/projectile/special/rocket.dm
Labels: Balance

#341 removes Skooma from the game + removes a bunch of drugs from plants.
  code/modules/fallout/reagents/drugs.dm
  code/modules/reagents/chemistry/machinery/reagentgrinder.dm
  code/modules/reagents/chemistry/reagents/drug_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/recipes/drugs.dm
Labels: Removal

#344 Adjusts sonic jackhammer time and adds a sound
  code/game/turfs/simulated/wall/reinf_walls.dm
Labels: Balance

#339 Super-stim and healing poultice buff
  code/modules/movespeed/modifiers/mobs.dm
Labels: Balance

#338 Bitter drink nerf
  code/modules/fallout/reagents/medicines.dm
Labels: Balance

#336 Legio_invicta_part1
  _maps/map_files/Temp Map Storage/RedRiver.dmm
  atombomb.dme
  code/game/objects/items/cards_ids.dm
  code/game/objects/items/melee/f13onehanded.dm
  code/game/objects/items/melee/f13powerfist.dm
  code/game/objects/items/melee/f13twohanded.dm
  code/game/objects/items/storage/belt.dm
  code/modules/clothing/glasses/f13.dm
  code/modules/clothing/gloves/f13gloves.dm
  code/modules/clothing/masks/miscellaneous.dm
  code/modules/jobs/job_types/legion.dm
  icons/fallout/clothing/glasses.dmi
  modular_atom/legio_invicta/README.md
  modular_atom/legio_invicta/code/legio_invicta.dm
  modular_atom/legio_invicta/icons/64x64_lefthand.dmi
  modular_atom/legio_invicta/icons/64x64_righthand.dmi
  modular_atom/legio_invicta/icons/backslot.dmi
  modular_atom/legio_invicta/icons/beltslot.dmi
  modular_atom/legio_invicta/icons/icons_64x32_legion.dmi
  modular_atom/legio_invicta/icons/icons_legion.dmi
  modular_atom/legio_invicta/icons/onmob_legion.dmi
  modular_atom/legio_invicta/icons/onmob_legion_lefthand.dmi
  modular_atom/legio_invicta/icons/onmob_legion_righthand.dmi
Labels: Feature, Sprites

#350 Removes extra damage when you equip melee weapons
  code/game/objects/items/melee/f13onehanded.dm
Labels: Balance

#335 adds gauss pistol
  code/modules/projectiles/boxes_magazines/external/rifle.dm
  code/modules/projectiles/guns/ballistic/pistol.dm
  code/modules/research/designs/ammolathe_designs.dm
  icons/fallout/objects/guns/ballistic.dmi
Labels: Feature, Sprites

#359 Weapon vendor fix
  code/modules/WVM/wvm.dm
Labels: Bugfix

#361 Guns eject casings on the same tile they were fired from.
  code/modules/projectiles/guns/ballistic.dm
Labels: Code Optimization/Refactor

#365 Interlude
  code/__DEFINES/inventory.dm
  code/_globalvars/lists/maintenance_loot.dm
  code/game/objects/effects/spawners/f13lootdrop.dm
  code/modules/antagonists/wizard/equipment/artefact.dm
  code/modules/clothing/gloves/f13gloves.dm
  code/modules/clothing/neck/apron.dm
  code/modules/clothing/neck/mantle.dm
  code/modules/clothing/shoes/f13.dm
  code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
  code/modules/jobs/job_types/legion.dm
  modular_atom/fashion/code/cosmetics.dm
  modular_atom/fashion/icons/hair_extensions.dmi
  modular_atom/fashion/icons/onmob.dmi
  modular_atom/legio_invicta/code/legio_invicta.dm
  modular_atom/legio_invicta/icons/beltslot.dmi
  modular_atom/legio_invicta/icons/icons_legion.dmi
  modular_atom/legio_invicta/icons/onmob_legion.dmi
  modular_atom/legio_invicta/icons/onmob_legion_lefthand.dmi
  modular_atom/legio_invicta/icons/onmob_legion_righthand.dmi
  modular_citadel/code/modules/client/loadout/shoes.dm
Labels: Bugfix, Sprites, Code Optimization/Refactor

#360 Reworks SGT loadouts
  code/modules/jobs/job_types/ncr.dm
  icons/obj/clothing/accessories.dmi
Labels: Balance

#340 THE... Shield Nerf
  code/game/objects/items/shields.dm
Labels: Balance

#354 Loot Spawner Organisation
  _maps/map_files/Mohave-Valley-Lower.dmm
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
  _maps/map_files/generic/CentCom.dmm
  code/game/objects/effects/spawners/f13lootdrop.dm
  code/game/objects/effects/spawners/themed_loot_tables.dm
  code/modules/fallout/obj/spawners/lootdrops.dm
  icons/effects/landmarks_static.dmi
Labels: Mapping, Sprites, Code Optimization/Refactor

#363 Fixes mobs not firing multiple projectiles, supposedly + other mob tweaks
  code/__DEFINES/combat.dm
  code/modules/mob/living/simple_animal/hostile/f13/Securitron.dm
  code/modules/mob/living/simple_animal/hostile/f13/eyebot.dm
  code/modules/mob/living/simple_animal/hostile/f13/wastebots.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
Labels: Bugfix

#322 eastwood less ugly
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
  code/__DEFINES/access.dm
  code/__DEFINES/jobs.dm
  code/game/machinery/computer/card.dm
  code/game/machinery/computer/robot.dm
  code/game/objects/effects/landmarks.dm
  code/game/objects/items/cards_ids.dm
  code/game/objects/items/devices/radio/encryptionkey.dm
  code/game/objects/items/devices/radio/headset.dm
  code/modules/jobs/access.dm
  code/modules/jobs/job_types/eastwood.dm
  code/modules/jobs/jobs.dm
  code/modules/mob/living/brain/posibrain.dm
  code/modules/mob/living/silicon/robot/robot_defines.dm
  code/modules/mob/living/simple_animal/bot/bot.dm
  code/modules/mob/living/simple_animal/bot/cleanbot.dm
  code/modules/mob/living/simple_animal/bot/firebot.dm
  code/modules/mob/living/simple_animal/bot/floorbot.dm
  code/modules/mob/living/simple_animal/bot/medbot.dm
  code/modules/modular_computers/file_system/programs/borg_monitor.dm
  code/modules/modular_computers/file_system/programs/powermonitor.dm
  code/modules/modular_computers/file_system/programs/robocontrol.dm
  code/modules/power/apc.dm
  code/modules/power/singularity/collector.dm
  code/modules/power/singularity/emitter.dm
  code/modules/research/nanites/nanite_remote.dm
  code/modules/vehicles/mecha/mech_fabricator.dm
  code/modules/vehicles/mecha/mecha_control_console.dm
Labels: Mapping

#194 Alchemy table
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
  code/__DEFINES/tools.dm
  code/datums/components/crafting/recipes/recipes_medicine.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/modules/reagents/chemistry/machinery/chem_master.dm
  icons/fallout/structures/alchemy.dmi
Labels: stale, Feature, Sprites

#345 Removes static PA
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
  code/game/objects/effects/spawners/f13lootdrop.dm
Labels: Mapping, Removal

#331 Adds button to go directly to the rules
  code/controllers/configuration/entries/general.dm
  config/config.txt
  interface/interface.dm
  interface/skin.dmf
Labels: Feature

#259 adds chinese language and chinese raider loadout, (changed to type 17 pistol you fun police)
  atombomb.dme
  code/datums/traits/good.dm
  code/modules/clothing/suits/suit_fashion.dm
  code/modules/jobs/job_types/wasteland.dm
  code/modules/language/chinese.dm
  icons/misc/language.dmi
Labels: stale, Feature, Feedback Required (DNM)

#383 verminkiller sprite fix
  code/modules/projectiles/guns/ballistic/rifle.dm
Labels: Bugfix

#379 Armor sets trial
  code/game/objects/items/melee/f13twohanded.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/tools/screwdriver.dm
  code/game/objects/items/tools/weldingtool.dm
  code/game/objects/items/tools/wirecutters.dm
  code/modules/clothing/glasses/f13.dm
  code/modules/clothing/head/f13factionhead.dm
  code/modules/clothing/suits/medium_armor.dm
  code/modules/jobs/job_types/legion.dm
  modular_atom/blacksmith/additions.dm
  modular_atom/blacksmith/anvil.dm
  modular_atom/blacksmith/icons/onmob/lefthand.dmi
  modular_atom/blacksmith/icons/onmob/righthand.dmi
  modular_atom/legio_invicta/README.md
  modular_atom/legio_invicta/code/legio_invicta.dm
  modular_atom/legio_invicta/icons/backslot.dmi
  modular_atom/legio_invicta/icons/icons_legion.dmi
  modular_atom/legio_invicta/icons/onmob_legion.dmi
  modular_atom/legio_invicta/icons/onmob_legion_lefthand.dmi
  modular_atom/legio_invicta/icons/onmob_legion_righthand.dmi
Labels: Feature, Sprites

#376 changes how healstacking is prevented
  code/modules/fallout/reagents/medicines.dm
Labels: Bugfix

#395 LOOCBAN
  code/modules/admin/admin.dm
  code/modules/client/verbs/looc.dm
Labels: Code Optimization/Refactor

#352 lore-accurate rangemaster + low-tier plasma pistol
  code/game/objects/effects/spawners/f13lootdrop.dm
  code/modules/projectiles/ammunition/caseless/_caseless.dm
  code/modules/projectiles/boxes_magazines/ammo_boxes.dm
  code/modules/projectiles/boxes_magazines/internal/misc.dm
  code/modules/projectiles/boxes_magazines/internal/shotgun.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/guns/energy/plasmaf13.dm
  code/modules/projectiles/guns/hoboguns.dm
  code/modules/projectiles/projectile/beams.dm
  icons/fallout/objects/guns/ballistic.dmi
  icons/fallout/objects/guns/energy.dmi
  icons/obj/guns/projectile.dmi
Labels: Balance, Sprites

#372 Sniper category fire delay change + some small fixes
  code/__DEFINES/combat.dm
  code/game/objects/effects/spawners/themed_loot_tables.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/guns/hoboguns.dm
Labels: Balance

#382 fixes legate
  code/modules/jobs/job_types/legion.dm
Labels: Bugfix

#385 Disables weather for now
  code/controllers/subsystem/processing/weather.dm
Labels: Removal

#388 Removing infinite money plants
  code/modules/food_and_drinks/food/snacks_pie.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_pie.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_salad.dm
  code/modules/hydroponics/grown/apple.dm
  code/modules/hydroponics/grown/melon.dm
  code/modules/jobs/job_types/eastwood.dm
Labels: Bugfix

#389 RnD bugfix
  code/modules/research/destructive_analyzer.dm
Labels: Bugfix

#384 nerfs bottled patron, changes goldschlager ratio
  code/modules/WVM/wmv_buyer.dm
  code/modules/food_and_drinks/recipes/drinks/drinks_alcoholic.dm
Labels: Balance

#380 Massive map changes (Includes Follower access changes)
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
  code/modules/vending/cola.dm
Labels: Mapping, Code Optimization/Refactor

#390 BOS elevator fix
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
  _maps/shuttles/bos_elevator.dmm
  _maps/shuttles/entrance_elevator.dmm
Labels: Bugfix, Mapping

#397 Hole in the map fix
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
Labels: Bugfix

#391 Revert "Hobomat 2 electric boogaloo"
  code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
  code/modules/projectiles/boxes_magazines/internal/rifle.dm
  code/modules/projectiles/guns/ballistic/rifle.dm
  code/modules/projectiles/guns/hoboguns.dm
  icons/fallout/objects/guns/longguns.dmi
  icons/fallout/onmob/weapons/guns_lefthand.dmi
  icons/fallout/onmob/weapons/guns_righthand.dmi
Labels: Balance

#399 Fixes magneto/rangemaster guns
  icons/fallout/objects/guns/ballistic.dmi
  icons/fallout/objects/guns/energy.dmi
  icons/obj/guns/projectile.dmi
Labels: Bugfix, Sprites

#410 First PR,Doing some changes with bayonet bloat
  code/modules/jobs/job_types/ncr.dm
Labels: Balance

#377 brush gun buff take two
  code/modules/projectiles/guns/ballistic/rifle.dm
Labels: Balance

#412 Adds some extra net-speak words in the filter
  config/in_character_filter.txt
Labels: Code Optimization/Refactor

#411 Re-adds the Knucklegun, Knifegun and Zip gun recipes back
  code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
Labels: Feature

#409 Removes Digitigrade legs from spawning on corpses
  code/__HELPERS/mobs.dm
Labels: Bugfix

#406 Nerfs smithing force
  modular_atom/blacksmith/additions.dm
Labels: Balance

#402 Re-names the Knight-Captain back to Head Knight + some fixes
  code/__DEFINES/jobs.dm
  code/game/machinery/computer/card.dm
  code/game/objects/effects/landmarks.dm
  code/modules/WVM/wmv_buyer.dm
  code/modules/clothing/head/f13factionhead.dm
  code/modules/clothing/suits/medium_armor.dm
  code/modules/clothing/under/accessories.dm
  code/modules/jobs/access.dm
  code/modules/jobs/job_types/bos.dm
  code/modules/jobs/jobs.dm
  icons/fallout/clothing/armored_medium.dmi
  icons/fallout/clothing/hats.dmi
  icons/obj/clothing/accessories.dmi
  modular_citadel/code/modules/client/loadout/head.dm
  modular_citadel/code/modules/client/loadout/uniform.dm
Labels: Removal, Feature, Sprites

#415 Various bug fixes
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
  code/datums/traits/_quirk.dm
  code/datums/wounds/_scars.dm
  code/datums/wounds/_wounds.dm
  code/game/turfs/simulated/water.dm
  code/modules/clothing/under/accessories.dm
  code/modules/fallout/misc/gang_items.dm
  code/modules/fallout/turf/ground.dm
  code/modules/projectiles/guns/misc/medbeam.dm
  icons/fallout/objects/medicine/drugs.dmi
  modular_citadel/code/modules/client/loadout/head.dm
  modular_citadel/code/modules/client/loadout/suit.dm
Labels: Bugfix, Mapping, Sprites

#407 Rubbery shotgun nerf
  code/__DEFINES/combat.dm
  code/modules/projectiles/projectile/bullets/shotgun.dm
Labels: Balance

#408 Recoil Adjustment
  code/__DEFINES/armor.dm
  code/__DEFINES/combat.dm
  modular_coyote/eris/code/living_recoil.dm
Labels: Balance
