Repository AtomBombf13/AtomBomb, pull requests merged in 2023-01, with the labels that each got.

#414 Fixed Mayor and Commerce Freq, added both servers to Sunset-Lower.dmm
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
  code/__DEFINES/radio.dm
  code/controllers/subsystem/blackbox.dm
  code/game/machinery/telecomms/machines/bus.dm
  code/game/machinery/telecomms/machines/hub.dm
  code/game/machinery/telecomms/machines/server.dm
  code/game/objects/items/devices/radio/encryptionkey.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/say.dm
  code/modules/jobs/job_types/eastwood.dm
  interface/stylesheet.dm
  tgui/packages/tgui-panel/chat/constants.js
  tgui/packages/tgui-panel/styles/goon/chat-dark.scss
  tgui/packages/tgui-panel/styles/goon/chat-light.scss
  tgui/public/tgui-panel.bundle.css
  tgui/public/tgui-panel.bundle.js
Labels: Bugfix

#421 AMR Fix / Auto-Pump Nerf
  code/__DEFINES/combat.dm
  code/modules/projectiles/guns/ballistic/rifle.dm
Labels: Balance

#420 Tweaks faction loadout items and fixes most of the unused job names in job
  code/datums/traits/negative.dm
  code/game/objects/items/cards_ids.dm
  code/game/objects/items/storage/boxes.dm
  code/modules/jobs/access.dm
  code/modules/jobs/jobs.dm
  modular_citadel/code/modules/client/loadout/head.dm
  modular_citadel/code/modules/client/loadout/shoes.dm
  modular_citadel/code/modules/client/loadout/suit.dm
  modular_citadel/code/modules/client/loadout/uniform.dm
Labels: Bugfix, Feature

#422 Second round of smithing nerfs + Parry
  code/datums/materials/basemats.dm
  modular_atom/blacksmith/additions.dm
  modular_atom/blacksmith/backup/(FOR CITADEL WIELDING)finished_items.dm
  modular_atom/blacksmith/finished_items.dm
Labels: Balance

#332 Letpassthrow update
  code/_onclick/adjacent.dm
  code/controllers/subsystem/throwing.dm
  code/game/machinery/deployable.dm
  code/game/machinery/doors/unpowered.dm
  code/game/objects/items/stacks/rods.dm
  code/game/objects/structures/loot_pile.dm
  code/game/objects/structures/morgue.dm
  code/game/objects/structures/tables_racks.dm
  code/game/turfs/f13concrete.dm
  code/modules/fallout/obj/structures/obstacle.dm
  code/modules/fallout/obj/structures/simple_door.dm
  code/modules/farming/farming_structures.dm
  code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
  code/modules/hydroponics/grown/towercap.dm
Labels: Bugfix

#393 Removes security vests from Eastwood armory, and buffs heavy bulletproof vest
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
  code/modules/clothing/suits/heavy_armor.dm
  code/modules/clothing/suits/medium_armor.dm
Labels: Balance, Mapping

#428 Head Knight armor fix
  icons/fallout/onmob/clothes/armor_medium.dmi
  icons/fallout/onmob/clothes/head.dmi
Labels: Bugfix

#432 BUGFIX - Renegades fix
  modular_sunset/code/mob/renegade.dm
Labels: Bugfix

#425 Gives the Head Knight a command headset
  code/modules/jobs/job_types/bos.dm
Labels: Feature

#435 Replaces spiders with Cockroaches.
  code/modules/hydroponics/hydroponics.dm
Labels: Feature

#445 steel helmet quick fix
  code/modules/clothing/head/helmet.dm
Labels: Bugfix

#439 nerfs ESD rounds
  code/modules/projectiles/projectile/bullets/rifle.dm
Labels: Balance

#437 nuka years resolution: return to PRs
  code/modules/fallout/reagents/drinks.dm
Labels: Feature

#436 Powerfist Buff
  code/game/objects/items/melee/f13powerfist.dm
Labels: Balance

#442 Food code sweep up + new chocolate for the heart chocolate box
  atombomb.dme
  code/game/objects/items/storage/fancy.dm
  code/modules/fallout/obj/food_and_drinks/food.dm
  code/modules/food_and_drinks/food/snacks_bread.dm
  code/modules/food_and_drinks/food/snacks_burgers.dm
  code/modules/food_and_drinks/food/snacks_cake.dm
  code/modules/food_and_drinks/food/snacks_egg.dm
  code/modules/food_and_drinks/food/snacks_frozen.dm
  code/modules/food_and_drinks/food/snacks_meat.dm
  code/modules/food_and_drinks/food/snacks_mexican.dm
  code/modules/food_and_drinks/food/snacks_other.dm
  code/modules/food_and_drinks/food/snacks_packaged.dm
  code/modules/food_and_drinks/food/snacks_pastry.dm
  code/modules/food_and_drinks/food/snacks_pie.dm
  code/modules/food_and_drinks/food/snacks_pizza.dm
  code/modules/food_and_drinks/food/snacks_salad.dm
  code/modules/food_and_drinks/food/snacks_sandwichtoast.dm
  code/modules/food_and_drinks/food/snacks_soup.dm
  code/modules/food_and_drinks/food/snacks_spaghetti.dm
  code/modules/food_and_drinks/food/snacks_sushi.dm
  code/modules/food_and_drinks/food/snacks_sweets.dm
  code/modules/food_and_drinks/food/snacks_vegetables.dm
  code/modules/food_and_drinks/food/snacks_vend.dm
  code/modules/food_and_drinks/pizzabox.dm
  icons/obj/food/food.dmi
Labels: Code Optimization/Refactor

#452 Legion Fortress
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
  code/__DEFINES/footsteps.dm
  code/datums/components/crafting/guncrafting.dm
  code/game/machinery/doors/unpowered.dm
  code/game/objects/effects/landmarks.dm
  code/game/objects/items/melee/f13twohanded.dm
  code/game/objects/structures/bedsheet_bin.dm
  code/game/objects/structures/fireplace.dm
  code/game/objects/structures/watercloset.dm
  code/modules/fallout/areas/area.dm
  code/modules/fallout/obj/campfire.dm
  code/modules/fallout/turf/ground.dm
  code/modules/hydroponics/grown/towercap.dm
  code/modules/jobs/job_types/legion.dm
  code/modules/surgery/tools.dm
  icons/fallout/objects/furniture/chairs_and_beds.dmi
  icons/fallout/objects/furniture/heating.dmi
  icons/fallout/structures/doors.dmi
  icons/fallout/turfs/gravel.dmi
  icons/fallout/turfs/walls/tents.dmi
  icons/mob/landmarks.dmi
  icons/obj/crates.dmi
  icons/turf/areas.dmi
  modular_atom/blacksmith/additions.dm
  modular_atom/blacksmith/backup/(FOR CITADEL WIELDING)finished_items.dm
  modular_atom/blacksmith/backup/(FOR CITADEL WIELDING)smithed_items.dm
  modular_atom/fashion/icons/hair.dmi
  modular_atom/kitchen_50s/code/kitchen_50s.dm
  modular_atom/kitchen_50s/icons/icons_kitchen.dmi
  modular_atom/legio_invicta/code/legio_invicta.dm
  modular_atom/legio_invicta/icons/64x64_icons.dmi
  modular_atom/legio_invicta/icons/backslot.dmi
  modular_atom/legio_invicta/icons/icons_legion.dmi
  modular_atom/legio_invicta/icons/onmob_legion.dmi
  modular_atom/legio_invicta/icons/onmob_legion_lefthand.dmi
  modular_atom/legio_invicta/icons/onmob_legion_righthand.dmi
Labels: Mapping, Feature

#398 Faction currency re-enabled, money buff, vending prices adjusted, added money printers to map
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
  atombomb.dme
  code/__DEFINES/economy.dm
  code/_globalvars/lists/maintenance_loot.dm
  code/game/machinery/doors/airlock_electronics.dm
  code/game/machinery/doors/firedoor.dm
  code/game/machinery/firealarm.dm
  code/game/objects/effects/spawners/f13lootdrop.dm
  code/game/objects/items/RCD.dm
  code/game/objects/items/devices/flashlight.dm
  code/game/objects/items/kitchen.dm
  code/game/objects/items/melee/f13onehanded.dm
  code/game/objects/items/stacks/tape.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/items/storage/fancy.dm
  code/modules/WVM/wmv_buyer.dm
  code/modules/WVM/wvm.dm
  code/modules/atmospherics/machinery/airalarm.dm
  code/modules/clothing/ears/_ears.dm
  code/modules/clothing/gloves/color.dm
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/fallout/obj/stack/f13Cash.dm
  code/modules/fallout/obj/trash_stack.dm
  code/modules/food_and_drinks/drinks/drinks.dm
  code/modules/food_and_drinks/drinks/drinks/bottle.dm
  code/modules/food_and_drinks/food/snacks_vend.dm
  code/modules/jobs/job_types/legion.dm
  code/modules/jobs/job_types/wasteland.dm
  code/modules/mining/money_bag.dm
  code/modules/mob/living/simple_animal/hostile/f13/ghoul.dm
  code/modules/mob/living/simple_animal/hostile/f13/raider.dm
  code/modules/power/cable.dm
  code/modules/vending/_vending.dm
  code/modules/vending/autodrobe.dm
  code/modules/vending/cartridge.dm
  code/modules/vending/cigarette.dm
  code/modules/vending/coffee.dm
  code/modules/vending/cola.dm
  code/modules/vending/dinnerware.dm
  code/modules/vending/engineering.dm
  code/modules/vending/f13nukacola.dm
  code/modules/vending/games.dm
  code/modules/vending/medical.dm
  code/modules/vending/medical_wall.dm
  code/modules/vending/megaseed.dm
  code/modules/vending/nutrimax.dm
  code/modules/vending/snack.dm
  code/modules/vending/wardrobes.dm
  code/modules/vending/youtool.dm
  icons/WVM/new_vendors.dmi
  modular_sunset/code/mob/renegade.dm
  tgui/packages/tgui/interfaces/Vending.js
Labels: Mapping, Feature, Sprites

#458 Cautery Fix
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
  code/modules/surgery/tools.dm
Labels: Bugfix

#454 Nerfs the Veteran Ranger's Sequoia
  code/modules/projectiles/guns/ballistic/revolver.dm
Labels: Balance

#473 Nerfs ESD ammo's stamina damage
  code/modules/projectiles/projectile/bullets/rifle.dm
Labels: Bugfix

#433 Gives every NCR a ration + changes to NCR Rep loadout
  code/game/objects/items/storage/lockbox.dm
  code/modules/clothing/head/power_armor.dm
  code/modules/clothing/suits/power_armor.dm
  code/modules/clothing/under/accessories.dm
  code/modules/jobs/job_types/ncr.dm
Labels: Feature, Sprites

#416 Changes HP's DKS + Glock to the Gauss Pistol.
  code/modules/jobs/job_types/bos.dm
  code/modules/projectiles/boxes_magazines/external/rifle.dm
  icons/fallout/objects/guns/ammo.dmi
Labels: Balance

#370 fixes weapon tweaks oversight /shrug
  code/modules/projectiles/ammunition/energy/laser.dm
  code/modules/projectiles/projectile/beams.dm
Labels: Balance

#441 Giving farmer roles seeds
  code/modules/jobs/job_types/bos.dm
  code/modules/jobs/job_types/eastwood.dm
  code/modules/jobs/job_types/legion.dm
  code/modules/jobs/job_types/ncr.dm
Labels: Feature

#444 Gives Paladins junior loadouts like Knights and Scribes
  code/modules/jobs/job_types/bos.dm
Labels: Feature

#434 Changes the Neohongo description + icon
  code/modules/language/neohongo.dm
  icons/misc/language.dmi
Labels: Code Optimization/Refactor

#400 pulse rifle rebalance + sprite fix
  code/game/objects/effects/spawners/f13lootdrop.dm
  code/modules/projectiles/guns/energy/special.dm
  code/modules/projectiles/projectile/special/ion.dm
  icons/mob/inhands/weapons/guns_lefthand.dmi
  icons/mob/inhands/weapons/guns_righthand.dmi
  icons/obj/guns/energy.dmi
Labels: Balance

#477 Pip for bootstrap
  tools/bootstrap/python36._pth
  tools/bootstrap/python_.ps1
Labels: Code Optimization/Refactor

#498 Fixing cyborg panel access
  code/modules/jobs/job_types/bos.dm
  code/modules/jobs/job_types/eastwood.dm
  code/modules/mob/living/silicon/robot/robot_defines.dm
Labels: Bugfix

#457 POSTERS FINALLY (Round 2)
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
  code/game/objects/effects/contraband.dm
  code/modules/fallout/obj/decor.dm
  icons/fallout/objects/decals.dmi
  icons/obj/contraband.dmi
Labels: Feature, Sprites

#481 fixes an unarmed bug
  code/game/objects/items/melee/f13onehanded.dm
Labels: Bugfix

#451 Minor Legion Loadout Additions
  code/modules/jobs/job_types/legion.dm
Labels: Balance

#465 Smelting & Camp polish
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
  code/__DEFINES/footsteps.dm
  code/game/machinery/deployable.dm
  code/game/machinery/doors/unpowered.dm
  code/game/machinery/iv_drip.dm
  code/game/objects/items/granters.dm
  code/game/objects/items/storage/bags.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/structures/fireplace.dm
  code/game/objects/structures/railings.dm
  code/game/turfs/f13concrete.dm
  code/game/turfs/simulated/minerals.dm
  code/modules/fallout/obj/campfire.dm
  code/modules/fallout/obj/structures/simple_door.dm
  code/modules/fallout/turf/ground.dm
  code/modules/jobs/job_types/legion.dm
  code/modules/reagents/reagent_containers/medspray.dm
  code/modules/surgery/tools.dm
  icons/effects/ore_visuals.dmi
  icons/fallout/turfs/gravel.dmi
  icons/fallout/turfs/wasteland.dmi
  icons/obj/iv_drip.dmi
  modular_atom/blacksmith/additions.dm
  modular_atom/blacksmith/furnace.dm
  modular_atom/blacksmith/icons/blacksmith.dmi
  modular_atom/fashion/code/cosmetics.dm
  modular_atom/icons/door_barred.dmi
  modular_atom/icons/fence.dmi
  modular_atom/icons/primitive_medical.dmi
  modular_atom/icons/stackable_items.dmi
  modular_atom/icons/tileset_gravel.dmi
  modular_atom/icons/tileset_sonora.dmi
  modular_atom/kitchen_50s/icons/icons_kitchen.dmi
  modular_atom/legio_invicta/code/legio_invicta.dm
  modular_atom/legio_invicta/icons/64x64_icons.dmi
  modular_atom/legio_invicta/icons/icons_legion.dmi
  modular_atom/legio_invicta/icons/onmob_legion.dmi
  modular_atom/sound/doorchainsoft_close.ogg
  modular_atom/sound/doorchainsoft_open.ogg
  modular_atom/sound/honey.ogg
Labels: Mapping

#471 Un-Akimbos the UZI SMG
  code/modules/projectiles/guns/ballistic/automatic.dm
Labels: Balance

#463 Gives orator access to the identity console
  code/game/machinery/computer/card.dm
Labels: Feature

#430 Reduces protectrons on the surface
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
Labels: stale, Mapping

#446 Tents come back & lower prices for tent vendor
  _maps/templates/shelter_1.dmm
  _maps/templates/shelter_10.dmm
  _maps/templates/shelter_2.dmm
  _maps/templates/shelter_3.dmm
  _maps/templates/shelter_6.dmm
  _maps/templates/shelter_7.dmm
  _maps/templates/shelter_8.dmm
  _maps/templates/shelter_9.dmm
  code/modules/WVM/wvm.dm
  code/modules/mining/equipment/survival_pod.dm
  code/modules/mining/shelters.dm
Labels: Feature

#480 adds the displacer glove and saturnite fist
  code/game/objects/items/melee/f13powerfist.dm
  icons/mob/inhands/weapons/melee_lefthand.dmi
  icons/mob/inhands/weapons/melee_righthand.dmi
  icons/obj/items_and_weapons.dmi
Labels: Feature, Sprites

#515 BBQ
  code/datums/components/crafting/recipes/recipes_assemblies.dm
  code/game/objects/items/cigs_lighters.dm
  code/game/objects/items/storage/boxes.dm
  code/modules/fallout/obj/campfire.dm
  code/modules/fallout/obj/food_and_drinks/food.dm
  code/modules/food_and_drinks/food/snacks/meat.dm
  code/modules/food_and_drinks/kitchen_machinery/grill.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_meat.dm
  icons/obj/food/food.dmi
  modular_atom/kitchen_50s/code/kitchen_50s.dm
  modular_atom/kitchen_50s/icons/icons_kitchen.dmi
  modular_atom/kitchen_50s/icons/kitchen32x64.dmi
  modular_atom/kitchen_50s/sound/campfire.ogg
  modular_atom/kitchen_50s/sound/cooking_short.ogg
Labels: Feature, Sprites

#462 Slightly Faster Paladin-Slayer Armour
  code/modules/clothing/suits/heavy_armor.dm
Labels: Balance

#492 Hydroponic sweep up + mushroom reorganization
  atombomb.dme
  code/modules/fallout/obj/food_and_drinks/drink.dm
  code/modules/fallout/obj/food_and_drinks/wastefood.dm
  code/modules/food_and_drinks/food/snacks_soup.dm
  code/modules/hydroponics/grown/agave.dm
  code/modules/hydroponics/grown/ambrosia.dm
  code/modules/hydroponics/grown/apple.dm
  code/modules/hydroponics/grown/banana.dm
  code/modules/hydroponics/grown/beans.dm
  code/modules/hydroponics/grown/berries.dm
  code/modules/hydroponics/grown/broc.dm
  code/modules/hydroponics/grown/buffalogourd.dm
  code/modules/hydroponics/grown/cannabis.dm
  code/modules/hydroponics/grown/cavefungus.dm
  code/modules/hydroponics/grown/cereals.dm
  code/modules/hydroponics/grown/chili.dm
  code/modules/hydroponics/grown/citrus.dm
  code/modules/hydroponics/grown/cocoa_vanilla.dm
  code/modules/hydroponics/grown/corn.dm
  code/modules/hydroponics/grown/coyotetobacco.dm
  code/modules/hydroponics/grown/cucumber.dm
  code/modules/hydroponics/grown/datura.dm
  code/modules/hydroponics/grown/eggplant.dm
  code/modules/hydroponics/grown/feracactus.dm
  code/modules/hydroponics/grown/flowers.dm
  code/modules/hydroponics/grown/garlic.dm
  code/modules/hydroponics/grown/grass_carpet.dm
  code/modules/hydroponics/grown/herbs.dm
  code/modules/hydroponics/grown/horsenettle.dm
  code/modules/hydroponics/grown/melon.dm
  code/modules/hydroponics/grown/mesquite.dm
  code/modules/hydroponics/grown/misc.dm
  code/modules/hydroponics/grown/mushrooms.dm
  code/modules/hydroponics/grown/mutfruit.dm
  code/modules/hydroponics/grown/nettle.dm
  code/modules/hydroponics/grown/olive.dm
  code/modules/hydroponics/grown/onion.dm
  code/modules/hydroponics/grown/peach.dm
  code/modules/hydroponics/grown/peanuts.dm
  code/modules/hydroponics/grown/peas.dm
  code/modules/hydroponics/grown/pineapple.dm
  code/modules/hydroponics/grown/pinyon.dm
  code/modules/hydroponics/grown/potato.dm
  code/modules/hydroponics/grown/prickly.dm
  code/modules/hydroponics/grown/pumpkin.dm
  code/modules/hydroponics/grown/punga.dm
  code/modules/hydroponics/grown/root.dm
  code/modules/hydroponics/grown/tato.dm
  code/modules/hydroponics/grown/tea_coffee.dm
  code/modules/hydroponics/grown/tobacco.dm
  code/modules/hydroponics/grown/tomato.dm
  code/modules/hydroponics/grown/towercap.dm
  code/modules/hydroponics/grown/xander.dm
  code/modules/hydroponics/grown/yucca.dm
  code/modules/mining/lavaland/ash_flora.dm
Labels: Code Optimization/Refactor

#464 removes mechs lol
  code/modules/research/techweb/nodes/mecha_nodes.dm
Labels: Removal
